version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.7.4
        environment:
          PIPENV_VENV_IN_PROJECT: true # creates .venv in project directory
    steps:
      - checkout
      - run:
          command: |
            pip --version
      - restore_cache:
          keys:
            - cache-{{ checksum "Pipfile.lock" }}
            - cache-
      - run:
          name: Install dependencies
          command: pipenv sync --dev
      - save_cache:
          key: cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache
      - run:
          command: |
            pipenv run pytest
