version: 2
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.7.4
        environment:
          PIPENV_VENV_IN_PROJECT: true # creates .venv in project directory
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ checksum "Pipfile.lock" }}
            - cache-
      - run:
          name: Install dependencies
          command: pipenv sync --dev
      - save_cache:
          key: cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache
      - run:
          command: |
            pipenv run pytest
  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.7.4
        environment:
          PIPENV_VENV_IN_PROJECT: true # creates .venv in project directory
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ checksum "Pipfile.lock" }}
            - cache-
      - run:
          name: Install dependencies
          command: pipenv sync
      - save_cache:
          key: cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache
      - run:
          name: Set up envvars for development spreadsheet
          command: |
            echo "export SPREADSHEET_ID=$DEVELOPMENT_SPREADSHEET_ID" >> $BASH_ENV
            echo "export SHEET_TITLE=$DEVELOPMENT_SHEET_TITLE" >> $BASH_ENV
            echo "export PROTECTED_RANGE_EDITOR_GROUPS=$DEVELOPMENT_PROTECTED_RANGE_EDITOR_GROUPS" >> $BASH_ENV
            echo "export PROTECTED_RANGE_EDITOR_USERS=$DEVELOPMENT_PROTECTED_RANGE_EDITOR_USERS" >> $BASH_ENV
      - run:
          name: Deploy to development spreadsheet
          command: |
            pipenv run python manager/main.py

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy_approval:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - deploy_approval
          filters:
            branches:
              only: master
